---
output: github_document
---

I develop a few R packages that rely on JavaScript libraries:

* [docsifier](https://docsifier.etiennebacher.com) (*adaptation of [docsify.js](https://docsify.js.org/#/)*): build a webpage for your documentation, whether it is an R package or an R project (alternative to `{pkgdown}`).

* [conductor](https://github.com/etiennebacher/conductor) (*adaptation of [shepherd.js](https://shepherdjs.dev/)*): create tours in Shiny apps.

* [shinyfullscreen](https://github.com/etiennebacher/shinyfullscreen) (*adaptation of [screenfull.js](https://github.com/sindresorhus/screenfull.js)*): display HTML elements in fullscreen in Shiny apps.

* [prompter](https://github.com/etiennebacher/prompter) (*adaptation of [hint.css](https://github.com/chinchang/hint.css)*): easily create tooltips in Shiny apps.

While developing these packages, I had some trouble trying to determine if a Javascript library had already been adapted in R. Therefore, I just started a list of R packages that adapt Javascript libraries, and you are invited to contribute! [Here's the list](https://github.com/etiennebacher/r-js-adaptation).

I also contribute to some R packages from the [**easystats**](https://github.com/easystats/) organization (mostly [datawizard](https://github.com/easystats/datawizard)).
